### ISSUE TITLE
没有对应的前端项目么？

### ISSUE THREAD

**Issue by maliqiang** [GoldSubmarine/submarine-admin-backend#1]
没有对应的前端项目么？

**Comment by Nayacco** [comment]
前端：https://github.com/GoldSubmarine/submarine-admin-frontend
建议明天重新fork，一直内部开发，没有上穿github，明天统一传一下

**Comment by Nayacco** [comment]
前后端都已上传

**Comment by zc-libre** [comment]
<dependency>
            <groupId>com.htnova</groupId>
            <artifactId>signature-server</artifactId>
            <version>1.0</version>
</dependency>
请问这个包在哪 怎么找不到

**Comment by Nayacco** [comment]
@zc150622 直接删掉就好了，相关代码也可以直接删，用于安卓签名的，内网的包，还没有发到公共仓库中
